name: Build Mac App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # Allows you to click a button to run it manually

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Get the code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Libraries
      run: |
        python -m pip install --upgrade pip
        pip install imageio-ffmpeg Pillow pyinstaller

    - name: Build the Mac App
      run: |
        pyinstaller --noconsole --onefile --collect-binaries imageio_ffmpeg app.py

    - name: Upload Finished App
      uses: actions/upload-artifact@v4
      with:
        name: SnapchatJoiner-Mac
        path: dist/